FROM python:3.12-slim

# Set Python environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    cron \
    wget \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install the required Python packages
RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
        pandas \
        psycopg2 \
        sqlalchemy \
        pycountry \
        pycountry_convert

# Copy .env file for the cron job
COPY ./docker/.env /etc/environment
        
# Copy Shell scripts for the cron job
COPY ./docker/scripts/run_feeder.sh /app/run_feeder.sh
COPY ./docker/scripts/run_pre_loader.sh /app/run_pre_loader.sh
COPY ./docker/scripts/run_delta_loader.sh /app/run_delta_loader.sh

# Copy Python scripts for the ETL & Feeder service
COPY ./sdu_qm_task/__init__.py /app/sdu_qm_task/__init__.py
COPY ./sdu_qm_task/connect.py /app/sdu_qm_task/connect.py
COPY ./sdu_qm_task/logger_conf.py /app/sdu_qm_task/logger_conf.py
COPY ./sdu_qm_task/etl /app/sdu_qm_task/etl
COPY ./sdu_qm_task/feeder /app/sdu_qm_task/feeder

COPY ./sdu_qm_task/queries/table_names.py \
        /app/sdu_qm_task/queries/table_names.py

COPY ./sdu_qm_task/queries/pre_loader_queries.py \
        /app/sdu_qm_task/queries/pre_loader_queries.py

COPY ./sdu_qm_task/queries/delta_loader_queries.py \
        /app/sdu_qm_task/queries/delta_loader_queries.py

# Set working directory
WORKDIR /app

# Add working directory to Path, Set PYTHONPATH
ENV PATH=/app:${PATH}
ENV PYTHONPATH=/app/sdu_qm_task

# Setup cron job
COPY ./docker/cronjob_etl /etc/cron.d/cronjob_etl

# Add cron job for scheduled execution
RUN crontab /etc/cron.d/cronjob_etl

# Give execution rights to the cron job
RUN chmod 0644 /etc/cron.d/cronjob_etl

# Create log file for tailing
RUN touch /var/log/cron.log

# Start cron in the foreground, tail the log to keep the container alive
CMD cron && tail -f /var/log/cron.log
